import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ReactNode } from "react";
import { auth } from "@/auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default async function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html>
            <body className={cn(inter.className, "min-h-dvh flex flex-col")}>
                <svg width="0" height="0">
                    <linearGradient id="te-gradient" x1="100%" y1="100%" x2="0%" y2="0%">
                        <stop stopColor="var(--destructive)" offset="0%" />
                        <stop stopColor="var(--primary)" offset="100%" />
                    </linearGradient>
                </svg>
                {children}
            </body>
        </html>
    );
}
