import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navigation/navbar";
import { Footer } from "@/components/navigation/footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "min-h-dvh flex flex-col")}>
                <NavBar />
                <main className="flex flex-col h-full flex-grow">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
