import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NavBar } from "@/components/navigation/navbar";
import { Footer } from "@/components/navigation/footer";
import { cn } from "@/lib/utils";
import { LocaleParams, getLang } from "@/locales/config";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children,
    params: { locale }
}: Readonly<{
    children: ReactNode;
    params: LocaleParams;
}>) {
    return (
        <html lang={getLang(locale)}>
            <body className={cn(inter.className, "min-h-dvh flex flex-col")}>
                <NavBar locale={locale} />
                <main className="flex flex-col h-full flex-grow">{children}</main>
                <Footer locale={locale} />
            </body>
        </html>
    );
}
