name: Next.js CI

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Generate Prisma
              run: npx prisma generate

            - name: Migrate Prisma
              run: npx prisma migrate dev
              env:
                  ADMIN_EMAIL: example@example.com

            - name: Next build
              run: npm run build
